galaxy_info:
  author: SmartOps.Academy
  description: Configure hosts, hostname, domain name on Debian/Ubuntu
  company: SmartOps Academy

  license: CC-BY-SA

  min_ansible_version: 2.4

  github_branch: https://github.com/SmartOpsAcademy/ansible/roles/hosts

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - debian
    - ubuntu
    - network
    - hostname

dependencies: []
