galaxy_info:
  author: SmartOps.Academy
  description: Installs and configures unattended upgrades to keep your server up to date.
  company: SmartOps Academy

  license: CC-BY-SA

  min_ansible_version: 2.4

  github_branch: https://github.com/SmartOpsAcademy/ansible/roles/unattended_upgrades

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - debian
    - ubuntu
    - upgrades
    - unattendedupgrades

dependencies: []
