galaxy_info:
  author: SmartOps.Academy
  description: Configures the APT repositories on a Debian/Ubuntu system
  company: SmartOps Academy

  license: CC-BY-SA

  min_ansible_version: 2.4

  github_branch: https://github.com/SmartOpsAcademy/ansible/roles/apt

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - debian
    - ubuntu
    - apt

dependencies: []
