galaxy_info:
  author: SmartOps.Academy
  description: Configures systemd timedatectl (timezone, NTP).
  company: SmartOps Academy

  license: CC-BY-SA

  min_ansible_version: 2.4

  github_branch: https://github.com/SmartOpsAcademy/ansible/roles/timedatectl

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - debian
    - ubuntu
    - timezone
    - ntp
    - ntpd
    - ntpdate
    - timesyncd
    - tzdata

dependencies: []
